[project]
name = "04-machine-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yonggyo1125", email = "yonggyo00@kakao.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "seaborn>=0.13.2",
]

[project.scripts]
04-machine-learning = "04_machine_learning:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
