[project]
name = "07-frontend-javascript"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yonggyo1125", email = "yonggyo00@kakao.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
07-frontend-javascript = "07_frontend_javascript:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
